from pptx import Presentation
from pptx.util import Inches, Pt
import os

def create_presentation():
    prs = Presentation()
    
    # 1. Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "AI Product Recommendation Engine"
    subtitle.text = "Personalizing the Shopping Experience\nDomain: E-Commerce\n\nGenerated by AI"
    
    # 2. Introduction
    bullet_slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    title_shape.text = "Introduction & Background"
    tf = body_shape.text_frame
    p = tf.add_paragraph()
    p.text = "The E-Commerce industry thrives on customer engagement and retention."
    p = tf.add_paragraph()
    p.text = "Shoppers are often overwhelmed by massive catalogs of thousands of products."
    p = tf.add_paragraph()
    p.text = "The cost of a poor shopping experience:"
    p2 = tf.add_paragraph()
    p2.text = "High bounce rates and abandoned carts."
    p2.level = 1
    p3 = tf.add_paragraph()
    p3.text = "Lost cross-selling and up-selling opportunities."
    p3.level = 1

    # 3. Problem Statement
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    title_shape.text = "Problem Statement & Objectives"
    tf = body_shape.text_frame
    p = tf.add_paragraph()
    p.text = "Problem: Customers struggle to find relevant products quickly, leading to lost sales."
    p = tf.add_paragraph()
    p.text = "Objective: Develop a highly accurate, automated AI Recommendation Engine."
    p = tf.add_paragraph()
    p.text = "Goals:"
    p2 = tf.add_paragraph()
    p2.text = "Increase Average Order Value (AOV)."
    p2.level = 1
    p3 = tf.add_paragraph()
    p3.text = "Surface hidden catalog items tailored to specific user tastes."
    p3.level = 1
    
    # 4. Proposed Solution
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    title_shape.text = "The Proposed AI Solution"
    tf = body_shape.text_frame
    p = tf.add_paragraph()
    p.text = "A Collaborative Filtering engine utilizing Nearest Neighbors (K-NN)."
    p = tf.add_paragraph()
    p.text = "Why Collaborative Filtering?"
    p2 = tf.add_paragraph()
    p2.text = "It doesn't require complex item metadata (descriptions, tags)."
    p2.level = 1
    p3 = tf.add_paragraph()
    p3.text = "It relies on the 'Wisdom of the Crowd': If User A and User B have similar tastes, User A will likely want what User B bought."
    p3.level = 1

    # 5. Dataset
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    title_shape.text = "User-Item Interaction Data"
    tf = body_shape.text_frame
    p = tf.add_paragraph()
    p.text = "The model was trained on a synthetic dataset representing E-commerce interactions."
    p = tf.add_paragraph()
    p.text = "Key Data Components:"
    p2 = tf.add_paragraph()
    p2.text = "Users: A pool of diverse shoppers (Tech enthusiasts, Fashion buyers, etc.)."
    p2.level = 1
    p3 = tf.add_paragraph()
    p3.text = "Products: A catalog of items identified by numerical IDs."
    p3.level = 1
    p4 = tf.add_paragraph()
    p4.text = "Ratings/Purchases: Implicit feedback indicating interest (Scale 1-5)."
    p4.level = 1

    # 6. Methodology
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    title_shape.text = "Machine Learning Methodology"
    tf = body_shape.text_frame
    p = tf.add_paragraph()
    p.text = "1. Data Generation: Simulating cluster-based shopping behavior."
    p = tf.add_paragraph()
    p.text = "2. Matrix Transformation: Pivoting raw data into a massive User-Item Matrix."
    p = tf.add_paragraph()
    p.text = "3. Dimensionality Setup: Handling sparse data efficiently."
    p = tf.add_paragraph()
    p.text = "4. Similarity Calculation: Using Cosine Similarity to measure angular distance between user vectors."
    p = tf.add_paragraph()
    p.text = "5. Recommendation Logic: Suggesting unseen items highly rated by the nearest neighbors."

    # 7. Model Architecture
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    title_shape.text = "Why Nearest Neighbors (Cosine Similarity)?"
    tf = body_shape.text_frame
    p = tf.add_paragraph()
    p.text = "Nearest Neighbors is a non-parametric method, perfect for memory-based recommendation."
    p = tf.add_paragraph()
    p.text = "Benefits for E-Commerce:"
    p2 = tf.add_paragraph()
    p2.text = "Cosine Similarity ignores the magnitude of vectors, focusing on the angle (pattern of ratings)."
    p2.level = 1
    p3 = tf.add_paragraph()
    p3.text = "It scales well when identifying user niches (e.g., finding the 5 most similar users out of thousands)."
    p3.level = 1

    # 8. Deployment
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    title_shape.text = "Interactive Dashboard (Streamlit)"
    tf = body_shape.text_frame
    p = tf.add_paragraph()
    p.text = "We built a web-based e-commerce simulator."
    p = tf.add_paragraph()
    p.text = "Features:"
    p2 = tf.add_paragraph()
    p2.text = "Select a specific User ID."
    p2.level = 1
    p3 = tf.add_paragraph()
    p3.text = "Adjust the desired number of product recommendations."
    p3.level = 1
    p4 = tf.add_paragraph()
    p4.text = "Instantly view top-ranked products calculated via collaborative filtering scores."
    p4.level = 1

    # 9. Conclusion
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    title_shape.text = "Conclusion & Retail Impact"
    tf = body_shape.text_frame
    p = tf.add_paragraph()
    p.text = "The AI Recommendation Engine effectively matches users with high-interest products."
    p = tf.add_paragraph()
    p.text = "Future Scope:"
    p2 = tf.add_paragraph()
    p2.text = "Implement Deep Learning (Neural Collaborative Filtering)."
    p2.level = 1
    p3 = tf.add_paragraph()
    p3.text = "Combine with Content-Based filtering (Hybrid Engine) to solve the 'Cold Start' problem."
    p3.level = 1
    p = tf.add_paragraph()
    p.text = "Ultimate Impact: Drastically improved user experience and increased revenue."

    prs.save('Project_Presentation.pptx')
    print("Extended Presentation saved as Project_Presentation.pptx")

if __name__ == "__main__":
    create_presentation()
